version: '3'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_data:/data
      - plex_temp:/transcode
      - plex_database:/config
    deploy:
      replicas: 1
    environment:
      - PLEX_CLAIM=claim-24DfzGrQc7p1sfK3F5x5
      - HOSTNAME=PlexServer
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    networks:
      - media
  transmission-daemon:
    image: dimanlin/transmission-daemon
    deploy:
      replicas: 1
    volumes:
      - transmission:/transmission
      # - plex_data:/transmission/download
    ports:
      - '51413:51413'
      - '9091:9091'
    networks:
      - media
networks:
  media:
volumes:
  plex_data:
  plex_temp:
  plex_database:
  transmission:
